### ISSUE TITLE
Serveur mattermost down ?

### ISSUE THREAD

**Issue by fcamblor** [CovidTrackerFr/mattermost-server#1]
Hello @nicolinuxfr, il semble que https://mattermost.covidtracker.fr/ soit dans les choux :-)
(impossible de se connecter au mattermost)

![mattermost_covidtracker_fr___522__Connection_timed_out](https://user-images.githubusercontent.com/603815/133052741-47923d6d-412b-4539-b914-b19bfb2c090e.png)

**Comment by nicolinuxfr** [comment]
Salut
En effet, je n'arrive pas à accéder au serveur. 

Et évidemment, ça tombe au moment où je suis en déplacement, j'ai un souci pour accéder au fournisseur, mais je m'en charge dès que possible.

**Comment by nicolinuxfr** [comment]
C’était bien un problème du côté de Scaleway, que Guillaume a pu régler dans la journée. Normalement, ça ne devrait plus se reproduire.

**Comment by fcamblor** [comment]
Merci :)
